#!/bin/bash
pkill dunst
dunst -config ~/.config/dunst/dunstrc &

notify-send -u critical "Test message:  
A citizen of America will cross the ocean to fight for democracy, but
won't cross the street to vote in a national election.
		-- Bill Vaughan"
notify-send -u normal "Test message: Where's the man could ease a heart
Like a satin gown?
		-- Dorothy Parker, The Satin Dress"

notify-send -u low "Test message: low test 3"
notify-send -u critical "Test message: critical test 4"
notify-send -u normal "Test message: normal test 5"
notify-send -u low "Test message: low test 6"
notify-send -u critical "Test message: critical test 7"
notify-send -u normal "Test message: normal test 8"
notify-send -u low "Test message: low test 9"
