[colors]
background = 00000000
bg-module = #121212
background-alt = #1a1a1a
foreground = #e6e6e6
primary = #B8BB26
secondary = #83A598
alert = #fb4934
disabled = #6272a4
Purple = #d3869b
Green = #689d69
Cyan = #8ec07c
Pink = #fabd2f
Blue = #83a598
orange = #fe8019

[bar/main]
monitor=${env:MONITOR:-eDP-1}
width = 100%
height = 20pt
radius = 14 
tray-position = right
tray-detached = false
tray-padding = 11
tray-maxsize=18
background = ${colors.background}
foreground = ${colors.foreground}
border-size = 2pt
border-color = #00000000
padding-left = 0
padding-right = 0
module-margin = 0
separator = ""
separator-foreground = ${colors.disabled}
;## font-0 = "JetBrainsMono:size=10:weight=bold;2"
;font-1 = "FontAwesome:size=10:weight=bold;2"
font-2 = "Ubuntu:size=10:weight=bold;2"
font-3 = "feather:size=10:weight=bold;2"
font-4 = "Iosevka:size=14:weight=bold;4"
; Bar layout
modules-left = esp i3
modules-center = p-esq date p-dir esp p-esq disk ram cpu wlan zerotier p-dir
modules-right = tray esp p-esq pulseaudio battery p-dir esp
font-0 = "Iosevka Nerd Font:pixelsize=10;3"
font-1 = "Iosevka Nerd Font:style=Medium:size=22;5"
enable-ipc = true

[module/i3]
type = internal/i3

; Focused workspace
label-focused = %index%
label-focused-foreground = ${colors.Purple}
label-focused-padding = 1

; Unfocused workspace
label-unfocused = %index%
label-unfocused-foreground = ${colors.foreground}
label-unfocused-padding = 1

; Visible workspace (on another monitor, if any)
label-visible = %index%
label-visible-foreground = ${colors.Purple}
label-visible-padding = 1

; Urgent workspace
label-urgent = %index%
label-urgent-foreground = ${colors.Red}
label-urgent-padding = 1

; Separator
label-separator = |
label-separator-foreground = ${colors.disabled}

[module/xwindow]
type = internal/xwindow
label = %title:0:10:...%

[module/tray]
type = internal/tray


[module/memory]
type = internal/memory
interval = 20
format-background = ${colors.bg-module}
format-prefix = " "
format-prefix-foreground = ${colors.Blue}
label = %{F#d8dee9}%percentage_used%%
label-padding-left = 1
label-padding-right = 3

[module/disk]
type = custom/script
exec = ~/.config/polybar/scripts/disk.sh
interval = 30
format-background = ${colors.bg-module}
label-padding-left = 1
label-padding-right = 2

[module/wlan]
type = custom/script
exec = ~/.config/polybar/scripts/wlan.sh
interval = 10
format-background = ${colors.bg-module}
label-padding-left = 1
label-padding-right = 2

[module/zerotier]
type = custom/script
exec = ~/.config/polybar/scripts/zt.sh
interval = 10
format-background = ${colors.bg-module}
label-padding-left = 1
label-padding-right = 2

[module/cpu]
type = internal/cpu
interval = 2
format-background = ${colors.bg-module}
format-prefix = " "
format-prefix-foreground = ${colors.Purple}
label = %{A1:gnome-terminal -e btop:}%{F#d8dee9}%percentage:2%%%{F-}%{A}
label-padding-left = 1
label-padding-right = 1

[module/pulseaudio]
type = internal/pulseaudio
format-volume-background = ${colors.bg-module}
format-volume-prefix = " "
format-volume-prefix-foreground = ${colors.orange}
format-volume = <label-volume>
label-volume = %{F#d8dee9}%percentage%%
label-muted = "  "
format-muted-background = ${colors.bg-module}
label-muted-foreground = ${colors.disabled}
label-padding-left = 1
label-padding-right = 3

[module/menu]
type = custom/script
format-background = ${colors.Cyan}
exec = echo "%{F#6272a4}  %{F-}%{F#16171d} "
click-left = bash -c "~/.config/rofi/launch.sh"

[module/date]
type = internal/date
interval = 1
format-background = ${colors.bg-module}
date =  %a, %d-%b  |  %R
label = %{A1:gnome-calendar:}%date%%{A}
label-padding-left = 1
label-padding-right = 0

[module/battery]
type = custom/script
format-background = ${colors.bg-module}
exec = ~/.config/polybar/scripts/battery.sh
interval = 15
scroll-up = brightnessctl set +5%
scroll-down = brightnessctl --min-value=10 set 5%-
label-padding-left = 1
label-padding-right = 1

[module/p-esq]
type = custom/text
content = ""
content-foreground = ${colors.bg-module}
content-font = 2

[module/p-dir]
type = custom/text
content = ""
content-foreground = ${colors.bg-module}
content-font = 2

[module/p-dir2]
type = custom/text
content = ""
content-foreground = ${colors.Cyan}
content-font = 2

[module/esp]
type = custom/text
content = "  "
content-foreground = ${colors.bg-module}
content-font = 2
